baseurl: https://ssabum.github.io/
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Ssabum's Devlog

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics: UA-194544565-1

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: ko

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: toy.ico

    footer:
        since: 2021
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 💻
        subtitle: Lazy beginner developer
        avatar:
            local: true
            src: img/image.jpg

    article:
        math: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: utterances

        utterances:
            repo: ssabum/comments
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
#        - identifier: home
#          name: Home
#          url: /
#          weight: -100
#          pre: home

        - identifier: algorithm
          name: Algorithm
          url: https://ssabum.github.io/categories/algorithm
          weight: -90
          pre: home

        - identifier: data
          name: Data
          url: https://ssabum.github.io/categories/data
          weight: -80
          pre: home

        - identifier: diary
          name: Diary
          url: https://ssabum.github.io/categories/diary
          weight: -70
          pre: home

        - identifier: til
          name: TIL
          url: https://ssabum.github.io/categories/til
          weight: -60
          pre: home

        - identifier: toy project
          name: Toy project
          url: https://ssabum.github.io/categories/toy-project
          weight: -50
          pre: home

        - identifier: github
          name: Github
          url: https://github.com/ssabum
          weight: -40
          pre: brand-github

#        - identifier: algorithm-study
#          name: AlgoStudy
#          url: https://github.com/ssabum/algorithm_study
#          weight: -40
#          pre: algorithm

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
